# LNDP# oct 28, 2016# demo scrape: the NYT!# the archive has 30m articles over 1851-present. # there are no terms of service issues with scraping the NYT public archive; scraping is not prohibited.# the archive freezes after 1000 results (100 pages), which is ~2 days. # so I'm going to tear down the browser every day.################### load libraries ###################import math                                                 # this lets you do mathfrom __future__ import division                             # this lets you divide numbers and get floating resultsimport re                                                   # this lets you make string replacements: 'hi there'.replace(' there') --> 'hi'import os                                                   # this lets you set system directoriesimport time                                                 # this lets you slow down your scraper so you don't crash the website =/import codecs                                               # symbols are annoying. this lets you replace them.import random                                               # this lets you draw random numbers.import datetime                                             # this lets you create a list of datesfrom datetime import timedelta                              # samefrom selenium import webdriver                              # the rest of these let you create your scraperfrom selenium.webdriver.common.keys import Keys from selenium.webdriver.common.by import Byfrom selenium.webdriver.support.ui import Selectfrom selenium.webdriver.support.ui import WebDriverWait#################### a basic example ####################print 'hello world!'1+1driver = webdriver.Firefox()url = 'http://www.google.com'driver.get(url)url = 'http://www.usc.edu'driver.get(url)driver.back()driver.refresh()driver.quit()########################## let's get this set up ########################### set your working directorywritedir = '/Users/erinbaggott/Desktop/NYTexample/'# set your writepathf = open(writedir+'test.txt','a') # set the dates you want to scrapestartdate = '20161020'enddate = '20161028'
# format your datedate = datetime.datetime.strptime(startdate, "%Y%m%d")while date <= datetime.datetime.strptime(enddate, "%Y%m%d"):    strdate = str(date).split(' ')[0].replace('-','')    print strdate    n = 1    driver = webdriver.Firefox()    driver.implicitly_wait(60)    url = 'http://query.nytimes.com/search/sitesearch/#/*/from'+strdate+'to'+strdate+'/document_type%3A%22blogpost%22/'+str(n)    driver.get(url)    time.sleep(random.uniform(5,10))
    if 'Sorry, your search returned no results.' in driver.page_source:
    	print 'no results'
    	driver.quit()
    	date += timedelta(days=1)
    	continue    # find # of results    rdiv = driver.find_element_by_id('totalResultsCount')    results = rdiv.text
    #print results    results = results.split(' Result')[0]
    results = results.split(' ')[(len(results.split(' '))-1)]
    print results
    if results>10:
    	r = int(results)/10
    	resultPages = math.ceil(r)
    if results<=10:
    	resultPages = 1    for page in range(1,int(resultPages)+1):        print 'page ' + str(page) + ' of ' + str(int(resultPages))        time.sleep(random.uniform(5,10))        div = driver.find_element_by_id('searchResults')        time.sleep(random.uniform(1,2))        text = div.text        if len(text)<50:            print 'text too short, break'            break; break        text = text.encode('utf-8')        f.write(text+'\n\n******************\n\n')        n += 1        suburl = 'http://query.nytimes.com/search/sitesearch/#/*/from'+strdate+'to'+strdate+'/document_type%3A%22blogpost%22/'+str(n)        driver.get(suburl)    date += timedelta(days=1)    driver.quit()f.close()